'''
Contains paths and other configurations for the flit installation.  This
particular file is from the git repository.  This file makes the files within
the git repository act as though it were an installation.  A new autogenerated
file will replace this version when an installation takes place.
'''

import os

all = [
    'version',
    'script_dir',
    'doc_dir',
    'lib_dir',
    'include_dir',
    'config_dir',
    'data_dir',
    'litmus_test_dir',
    ]

# flit scripts
script_dir = os.path.dirname(os.path.realpath(__file__))

# flit documentation
doc_dir = os.path.realpath(os.path.join(script_dir, '..', '..', 'documentation'))

# compiled libflit.so
lib_dir = os.path.realpath(os.path.join(script_dir, '..', '..', 'lib'))

# flit C++ include files, primarily flit.h
include_dir = os.path.realpath(os.path.join(script_dir, '..', '..', 'src'))

# default configuration for flit init
config_dir = os.path.join(script_dir, 'config')

with open(os.path.join(config_dir, 'version.txt'), 'r') as version_file:
    version = version_file.read().strip()

# default data files such as Makefiles
data_dir = os.path.join(script_dir, '..', '..', 'data')

# directory containing litmus tests
litmus_test_dir = os.path.realpath(os.path.join(script_dir, '..', '..', 'litmus-tests', 'tests'))

