'''
Contains paths and other configurations for the flit installation.  This
particular file is from the git repository.  This file makes the files within
the git repository act as though it were an installation.  A new autogenerated
file will replace this version when an installation takes place.
'''

import os

all = [
    'script_dir',
    'doc_dir',
    'lib_dir',
    'include_dir',
    ]

script_dir = os.path.dirname(os.path.realpath(__file__))
doc_dir = os.path.realpath(os.path.join(script_dir, '../../documentation'))
lib_dir = os.path.realpath(os.path.join(script_dir, '../../lib'))
include_dir = os.path.realpath(os.path.join(script_dir, '../../src'))
config_dir = os.path.join(script_dir, 'config')
