# -- LICENSE BEGIN --
#
# Copyright (c) 2015-2020, Lawrence Livermore National Security, LLC.
#
# Produced at the Lawrence Livermore National Laboratory
#
# Written by
#   Michael Bentley (mikebentley15@gmail.com),
#   Geof Sawaya (fredricflinstone@gmail.com),
#   and Ian Briggs (ian.briggs@utah.edu)
# under the direction of
#   Ganesh Gopalakrishnan
#   and Dong H. Ahn.
#
# LLNL-CODE-743137
#
# All rights reserved.
#
# This file is part of FLiT. For details, see
#   https://pruners.github.io/flit
# Please also read
#   https://github.com/PRUNERS/FLiT/blob/master/LICENSE
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the disclaimer below.
#
# - Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the disclaimer
#   (as noted below) in the documentation and/or other materials
#   provided with the distribution.
#
# - Neither the name of the LLNS/LLNL nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL LAWRENCE LIVERMORE NATIONAL
# SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#
# Additional BSD Notice
#
# 1. This notice is required to be provided under our contract
#    with the U.S. Department of Energy (DOE). This work was
#    produced at Lawrence Livermore National Laboratory under
#    Contract No. DE-AC52-07NA27344 with the DOE.
#
# 2. Neither the United States Government nor Lawrence Livermore
#    National Security, LLC nor any of their employees, makes any
#    warranty, express or implied, or assumes any liability or
#    responsibility for the accuracy, completeness, or usefulness of
#    any information, apparatus, product, or process disclosed, or
#    represents that its use would not infringe privately-owned
#    rights.
#
# 3. Also, reference herein to any specific commercial products,
#    process, or services by trade name, trademark, manufacturer or
#    otherwise does not necessarily constitute or imply its
#    endorsement, recommendation, or favoring by the United States
#    Government or Lawrence Livermore National Security, LLC. The
#    views and opinions of authors expressed herein do not
#    necessarily state or reflect those of the United States
#    Government or Lawrence Livermore National Security, LLC, and
#    shall not be used for advertising or product endorsement
#    purposes.
#
# -- LICENSE END --

'Implements the disguise subcommand to anonymize project-specific data'

import argparse
import csv
import subprocess as subp
import sys

brief_description = 'Anonymizes project-specific data from text files'

def populate_parser(parser=None):
    'Populate or create an ArgumentParser'
    if parser is None:
        parser = argparse.ArgumentParser()
    parser.description = '''
        This command disguises (a.k.a., anonymizes) text or log files.  Fields
        that can be disguised are source file names, test names, and function names.

        To accomplish this feat, a mapping csv file will either be provided by
        the user (with --disguise-map) or will be autogenerated as
        "disguise.csv" (default behavior) from the contents of the Makefile and
        the object files for the baseline compilation.  The mapping is applied
        as a very simple search and replace.

        To undo the disguise, use the --undo flag either allowing the default
        "disguise.csv" file to be used or specifying one with --disguise-map.
        '''
    parser.add_argument('-g', '--generate', action='store_true',
                        help='''
                            Just generate the disguise map as "disguise.csv"
                            and then exit.  It will be overwritten if it
                            already exists.  Most users will not need to use
                            this flag.
                            ''')
    parser.add_argument('-o', '--output',
                        help='''
                            Output the disguised version of the input file to
                            this specified file.  The default behavior is to
                            output to standard output.
                            ''')
    parser.add_argument('-m', '--disguise-map', default='disguise.csv',
                        help='''
                            Specify a specific CSV file to use as the disguise
                            map.  The CSV file is expected to have a header row
                            with the column names "value" and "disguise".  Both
                            columns should have unique values, i.e., a
                            one-to-one mapping.  The default is "disguise.csv"
                            which is autogenerated if it is not there.
                            ''')
    parser.add_argument('-u', '--undo', action='store_true',
                        help='''
                            Undo the disguising.  This will use the disguise
                            map to do search and replace in reverse.  For
                            example, this can be used to de-anonymize the
                            analysis done by someone with the anonymized
                            file(s).
                            ''')
    parser.add_argument('--fields', default='file,function,test',
                        help='''
                            A comma-separated list of fields you want to
                            disguise.  This will not effect the generated
                            disguise map, all fields will be present there.  It
                            will just impact the disguising and the undo
                            operations.

                            Available fields are
                            (1) "file": source file name and file path
                                (including compiled object file(s)),
                            (2) "function": function name, both mangled and
                                demangled, and
                            (3) "test": name of the test.
                            ''')
    parser.add_argument('file', nargs='?',
                        help='''
                            Text file to disguise.  Disguising is done with
                            simple search and replace.  The "value" column of
                            the disguise map CSV file is searched for and
                            replaced with the "value" field.  If --undo is
                            specified, then it is done in reverse.

                            If the file is not specified, then it is read from
                            standard in.
                            ''')
    return parser

def generate_disguise_map():
    'Generate the disguise map, often called from the Makefile'
    print('Created disguise.csv')
    with open('disguise.csv', 'w') as fout:
        fout.write('hello')

def check_disguise_map_regenerate():
    'check to see if disguise.csv needs regenerating and do it if so.'
    # TODO: implement
    #subp.check_call(['make', 'disguise.csv'])
    pass

def read_disguise_map(fname):
    'Read and return the forward and reverse dictionary of the disguise map'
    forward_map = {}
    reverse_map = {}
    with open(fname, 'r') as fin:
        reader = csv.DictReader(fin)
        assert 'disguise' in reader.fieldnames
        assert 'value' in reader.fieldnames
        for entry in reader:
            disguise, value = entry['disguise'], entry['value']
            assert disguise not in forward_map
            assert value not in reverse_map
            foward_map[disguise] = value
            reverse_map[value] = disguise
    return forward_map, reverse_map

def main(arguments, prog=None):
    'Main logic here'
    parser = populate_parser()
    if prog: parser.prog = prog
    args = parser.parse_args(arguments)

    # TODO: implement
    if args.generate:
        generate_disguise_map()
        return 0

    # TODO: implement
    if args.disguise_map == 'disguise.csv':
        check_disguise_map_regenerate()

    forward_map, reverse_map = read_disguise_map(args.disguise_map)

    # choose the output stream
    if args.output:
        out = open(args.output, 'w')
    else:
        out = sys.stdout

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
