#!/bin/bash

CLANG_ARCH := llvm_kp307_build.tgz
FLIT_DIR   := qfp
BRANCH     := unified_script

#SBATCH --time=1:00:00 
#SBATCH --nodes=1
#SBATCH -o ${HOME}/slurm-%j.out-%N 
#SBATCH -e ${HOME}/slurm-%j.err-%N 
#SBATCH --account=ganesh-kp
#SBATCH --partition=soc-kp

#setup working directory

WORKDIR := /tmp/${USER}

if [ ! -d ${WORKDIR}  ]; then
    mkdir -p ${WORKDIR}
    cd ${WORKDIR}
    git clone git://https://github.com/Geof23/QFP.git
fi

cd ${WORKDIR}
cd ${FLIT_DIR}
git checkout ${BRANCH}
git pull
cd ..

cp ${HOME}/${CLANG_ARCH} .

tar xf ${CLANG_ARCH}

cd ${FLIT_DIR}

scripts/hostCollect.sh

cd ../results

scp *.tgz ${DB_HOST}

