#!/bin/bash -x

#SBATCH --time=1:00:00 
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.err
#SBATCH --nodes 1
#SBATCH --account ganesh-kp
#SBATCH --partition soc-kp

CLANG_ARCH=llvm_kp307_build.tgz
FLIT_DIR=qfp
BRANCH=unified_script
DB_HOST=bihexal.cs.utah.edu
#setup working directory

WORKDIR=/tmp/${USER}
FDIR=${WORKDIR}/qfp
echo fdir is ${FDIR}

if [ -e ${FDIR} ]; then
    rm -fr ${FDIR}
fi

cd ${WORKDIR}
git clone -b ${BRANCH}  --recursive https://github.com/Geof23/qfp.git

cd ${FDIR}
git checkout ${BRANCH}
cd ..

cp ${HOME}/${CLANG_ARCH} .

tar xf ${CLANG_ARCH}

cd ${FLIT_DIR}

scripts/hostCollect.sh

cd ../results

scp *.tgz ${DB_HOST}

