#!/bin/bash
#required:
#BRANCH REPO FLIT_DIR CORES DB_USER DB_HOST
#[maybe] CUDA_ONLY and DO_PIN

#SBATCH --time=1:00:00 
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH -o slurm-flit-gpu-%j.out 
#SBATCH -e slurm-flit-gpu-%j.err 
#SBATCH --account=kingspeak-gpu
#SBATCH --partition=kingspeak-gpu
#SBATCH --gres=gpu:titanx:1

set -e

module load cuda
module load gcc

#setup working directory

export TMPD=$(mktemp -d)
cd ${TMPD}
mkdir ${FLIT_DIR}
cd ${FLIT_DIR}
cp ${PDIR}/flit.tgz .
tar xf flit.tgz

scripts/hostCollect.sh

cd /tmp
rm -fr ${TMPD}
rm -fr ${PDIR}
