name: Automated Tests

on:
  push:
    branches: [ devel, master, main ]
  pull_request:

jobs:
  automated-tests:
    runs-on: ubuntu-latest

    # matrix docs: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      matrix:
        include:
          - name: openmpi
            packages: libopenmpi-dev openmpi-bin
          - name: mpich
            packages: libmpich-dev mpich
          - name: none
            packages:

    steps:
      - name: install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install python3 python3-pip ${{ matrix.packages }} &&
          pip3 install --user setuptools toml
      - uses: actions/checkout@v2
      - name: build tests
        run: make -C tests -j ${{ steps.cpu-cores.outputs.count }}
      - name: run tests
        run: make check
